#ifndef STARSEA_PARAMETERS_H
#define STARSEA_PARAMETERS_H

#define PROJECT_NAME "starsea2"
#define WINDOW_NAME "StarSea2"

#define SCREEN_WIDTH   1280
#define SCREEN_HEIGHT  720
#define FRAME_RATE 30


#endif // STARSEA_PARAMETERS_H